### ISSUE TITLE
Traceback issue on webdriver chrome

### ISSUE THREAD

**Issue by GowthamNMk** [anirudhbagri/whatsapp-bulk-messenger#26]
What to do if traceback error error on coding line 61 ,25,57, 155

**Comment by GowthamNMk** [comment]
![image](https://user-images.githubusercontent.com/118333063/202092396-532c0ee1-b63a-4f4e-90f4-d793afdb528b.png)

Is there anyone has  solution for this?

**Comment by vivekarora56** [comment]
Update Selenium, in requirements change the version to 4.9.0

**Comment by superdidi-star** [comment]
We found 2 numbers in the file
Traceback (most recent call last):
  File "C:\Users\user\automator.py", line 61, in <module>
    driver = webdriver.Chrome(ChromeDriverManager().install(), options=options)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Lib\site-packages\webdriver_manager\chrome.py", line 34, in install
    driver_path = self._get_driver_path(self.driver)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Lib\site-packages\webdriver_manager\manager.py", line 23, in _get_driver_path
    driver_version = driver.get_version()
                     ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Lib\site-packages\webdriver_manager\driver.py", line 43, in get_version
    return self.get_latest_release_version()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Lib\site-packages\webdriver_manager\driver.py", line 67, in get_latest_release_version
    validate_response(resp)
  File "C:\Users\user\Lib\site-packages\webdriver_manager\utils.py", line 79, in validate_response
    raise ValueError("There is no such driver by url {}".format(resp.url))
ValueError: There is no such driver by url https://chromedriver.storage.googleapis.com/LATEST_RELEASE_128.0.6613

**Comment by superdidi-star** [comment]
Traceback (most recent call last):
  File "C:\Users\user\automator.py", line 61, in <module>
    driver = webdriver.Chrome(ChromeDriverManager().install(), options=options)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Lib\site-packages\webdriver_manager\chrome.py", line 34, in install
    driver_path = self._get_driver_path(self.driver)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Lib\site-packages\webdriver_manager\manager.py", line 23, in _get_driver_path
    driver_version = driver.get_version()
                     ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Lib\site-packages\webdriver_manager\driver.py", line 43, in get_version
    return self.get_latest_release_version()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Lib\site-packages\webdriver_manager\driver.py", line 67, in get_latest_release_version
    validate_response(resp)
  File "C:\Users\user\Lib\site-packages\webdriver_manager\utils.py", line 79, in validate_response
    raise ValueError("There is no such driver by url {}".format(resp.url))
ValueError: There is no such driver by url https://chromedriver.storage.googleapis.com/LATEST_RELEASE_128.0.6613

C:\Users\user>

i changed the Selenium, in requirements change the version to 4.9.0, but still show value error, can someone help?

**Comment by anirudhbagri** [comment]
This should fixed now.
